name: primavera_webapi
description: Pacote para acesso as funcionalidades do sistema ERP primavera v10.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  http: ^1.1.0
  uuid: ^4.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
